define
var _select_value = SELECTEDVALUE(select_value[value])

var _top_5_cat = TOPN(5,SUMMARIZE(SELECTCOLUMNS(ALLSELECTED('amazon-fashion - YT'),"cat",'amazon-fashion - YT'[NewCategory],"Sales Amount",[sale amount]),[cat]),[sale amount],DESC)

var _top_cat = CALCULATE(IF(SELECTEDVALUE(select_value[value])=="sales",[sale amount],[sale units]),KEEPFILTERS(_top_5_cat))
EVALUATE _top_cat