{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"gold prices\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1554.0 (23.12)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "742c6892-f418-44b3-88df-0fb2aacc68ac",
        "fromColumn": "Date",
        "fromTable": "Dtes",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4764007e-09b3-44b6-a803-380358ae4955"
      },
      {
        "name": "60157d20-aed0-4fab-89bc-4d1f8c5e805a",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Date",
        "fromTable": "gold prices",
        "toColumn": "Date",
        "toTable": "Dtes"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "gold prices",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "lineageTag": "5e159367-abb7-4531-8d79-50db22b6b5d0",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Close/Last",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "455fdf20-8dab-4e85-91e2-0ea3c3c37458",
            "sourceColumn": "Close/Last",
            "summarizeBy": "sum"
          },
          {
            "name": "Volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "94d32b4a-e1c5-4c86-9c6e-737cf2c50ac6",
            "sourceColumn": "Volume",
            "summarizeBy": "sum"
          },
          {
            "name": "Open",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6881bc93-836d-4b43-8a41-25cd21819763",
            "sourceColumn": "Open",
            "summarizeBy": "sum"
          },
          {
            "name": "High",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "014c7877-981d-4158-b7eb-fc8adb5f2fc7",
            "sourceColumn": "High",
            "summarizeBy": "sum"
          },
          {
            "name": "Low",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b0efb04d-ec9c-40ee-b373-444c1f4d4cc0",
            "sourceColumn": "Low",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "4f01e6ae-3273-4a2d-9710-45a4465c849f",
        "partitions": [
          {
            "name": "gold prices",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"D:\\Powerbi Project\\gold prices.csv\"),[Delimiter=\",\", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Date\", type date}, {\"Close/Last\", type number}, {\"Volume\", Int64.Type}, {\"Open\", type number}, {\"High\", type number}, {\"Low\", type number}}),",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Changed Type\", {\"Volume\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Errors\",{{\"Date\", type date}}),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Changed Type1\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null})))",
                "in",
                "    #\"Removed Blank Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_20583a82-f8df-4a27-acf9-f0ef767b2228",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1c385825-0dcc-496b-8ac3-2c58611a0c1a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "88acf832-8cd3-48b9-9dda-7ead224acf97",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "08e1143c-2dba-4a95-aefa-8b793e0f0a36",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4f5d786f-791f-40f1-8e9f-f977a04963d2",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "32e1749f-847c-46b2-a57b-4e89f97baa7d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "22d3c5e8-a87e-4702-9d8a-677929662607",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f0bd3041-ae53-44bf-b9b3-c219c499b25b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4306813d-e8b8-4ce2-810f-0a56f8af7734",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "29f3b54c-e1e0-414f-a692-3eef3ff1c844",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "1e4cc9b2-2ea6-4bdd-b19c-34c930eb2f94",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c51cde2b-de2f-49ba-93d7-1c9160ba5dcc",
                "ordinal": 3
              }
            ],
            "lineageTag": "8b96197f-9bd2-4e93-be42-5fa06003df8a"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "d852ba3f-129a-4659-b587-b7560d69f804",
        "partitions": [
          {
            "name": "DateTableTemplate_20583a82-f8df-4a27-acf9-f0ef767b2228",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Measure",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "90e175b071614aedaa1a1525c80d4795"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "192c5020-5443-4c16-973d-517a0fc3444e",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "1b0851e2-4070-4463-846c-a34bb05c8f89",
        "measures": [
          {
            "name": "Lows",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(max('gold prices'[Low]))",
            "lineageTag": "5053044a-f08c-4414-af5a-fe3447edfea5"
          },
          {
            "name": "Year high",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "max('gold prices'[High])",
            "lineageTag": "bfbc6def-03c2-4b9d-8f93-a05bd9edf05d"
          },
          {
            "name": "prev High",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(max('gold prices'[High]), SAMEPERIODLASTYEAR('gold prices'[Date]))",
            "lineageTag": "3f5a92a2-22c0-44aa-aff8-1090c9d78821"
          },
          {
            "name": "Previous Year Volume",
            "expression": "CALCULATE(sum('gold prices'[Volume]),SAMEPERIODLASTYEAR('gold prices'[Date]))",
            "formatString": "0",
            "lineageTag": "9d1366ee-fd0f-4e1a-869d-23ccbaf74aed"
          },
          {
            "name": "Percentage Change",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "([Year high]-[prev High])/[Year high]",
            "lineageTag": "83c2fa89-b888-48fc-89fb-92443ab23d53"
          },
          {
            "name": "Previous Low",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(max('gold prices'[Low]),SAMEPERIODLASTYEAR('gold prices'[Date]))",
            "lineageTag": "3dcd072d-5d89-4c4d-b8ac-7084930e8413"
          },
          {
            "name": "Percentage Change in low",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "([Lows]-[Previous Low])/[Lows]",
            "lineageTag": "9644ad80-e1e0-44dd-befe-c9eea7a15054"
          }
        ],
        "partitions": [
          {
            "name": "Measure",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dtes",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "acc3749e15244905a250f02f60557ff1"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d80b2984-badb-4162-912b-a0a129e077fa",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_4764007e-09b3-44b6-a803-380358ae4955"
                },
                "isDefault": true,
                "relationship": "742c6892-f418-44b3-88df-0fb2aacc68ac"
              }
            ]
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "year(Dtes[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "bcc47372-b224-48c2-b824-006ce6948009",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "month(Dtes[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "c4f85694-826a-4e4d-aeb6-2b34c23800a9",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "WeekDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "WEEKDAY(Dtes[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "be6fb6b5-cde6-49c9-b827-ff0dc066ffa6",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "DAY(Dtes[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "fa82fd68-7b1c-4d06-9475-59b1e350ec4b",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "44fd7748-3f02-4309-a6d8-5e67be71f3f6",
        "partitions": [
          {
            "name": "Dtes",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(min('gold prices'[Date]), max('gold prices'[Date]))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_4764007e-09b3-44b6-a803-380358ae4955",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "05cdc380-c445-46ff-8b36-d7c46175419c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "a5c33fc6-9fea-4538-aa7b-eacc760e9732",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "ca98d397-c8a6-4a18-9ad9-3c05d6ed8a0b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8e8c6f20-506b-4c81-8deb-b75655f415cd",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "5b434d57-cd71-44bd-9e13-6b224ade8a1c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "0ce94c39-dd6e-4ea7-aa8e-01e9d7e7fff0",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "8872cdca-5959-406b-a942-d40dcf40025c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "cadd459a-2c38-4436-8e84-64b5559256c0",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "807e8df8-9cce-42af-b5d4-d67072a33553",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0c9cc5a6-a4bc-48a1-a103-f93653194869",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2730b240-49c8-46a0-bd86-02599d31ab74",
                "ordinal": 3
              }
            ],
            "lineageTag": "29692ac2-e0f5-4f5b-8c35-880a7e799430"
          }
        ],
        "isHidden": true,
        "lineageTag": "509a87c2-394b-4a21-8298-b0d707796365",
        "partitions": [
          {
            "name": "LocalDateTable_4764007e-09b3-44b6-a803-380358ae4955",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Dtes'[Date])), 1, 1), Date(Year(MAX('Dtes'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}